"""Latchpoint Core package.

Deterministic policy gate for AI-generated diffs and structured
actions: policy loading, action validation, gate evaluation,
evidence packs with canonical JSON and stable SHA-256 hashes,
verify and replay, and an append-only ledger primitive. No I/O,
no clock, no randomness, no environment in the evaluation path.
"""

__version__ = "0.0.1"

from .action_model import (
    ACTION_ERROR_CATEGORIES,
    RISK_TIERS,
    ActionDescriptor,
    ActionError,
    resolve_field,
    validate_action,
)
from .adapters import (
    ADAPTER_ERROR_CATEGORIES,
    AdapterError,
    AdapterInput,
    AdapterOutput,
    AdapterProtocol,
    AdapterResult,
    SyntheticAdapter,
    adapt_payload,
)
from .evidence_model import (
    EVIDENCE_ERROR_CATEGORIES,
    POLICY_VERDICT_DECISIONS,
    DeterministicFacts,
    EvidenceError,
    EvidencePack,
    EvidencePackManifest,
    ModelDerivedJudgments,
    OverrideEvidence,
    PolicyVerdict,
    VerificationResult as EvidenceVerificationResult,
)
from .evidence_pack import (
    build_evidence_pack,
    evidence_pack_to_canonical_json,
    verify_evidence_pack,
)
from .evidence_verifier import (
    EvidenceVerifierResult,
    LedgerReplayMatch,
    verify_evidence,
)
from .gate_evaluator import evaluate_action
from .ledger import (
    GENESIS_PREV_HASH,
    LEDGER_ERROR_CATEGORIES,
    LedgerEntry,
    LedgerError,
    LedgerVerificationResult,
    append_ledger_entry,
    canonicalize_ledger_entry,
    compute_ledger_entry_hash,
    verify_ledger_chain,
)
from .gate_model import (
    GATE_EVALUATION_ERROR_CATEGORIES,
    GATE_STATUSES,
    GateEvaluation,
    GateEvaluationError,
    GateResult,
)
from .policy_loader import collect_errors
from .policy_model import (
    ERROR_CATEGORIES,
    AnyOf,
    Condition,
    Gate,
    Policy,
    PolicyError,
    ValidationResult,
)
from .safety_controls import (
    KILL_SWITCH_OUTCOMES,
    KILL_SWITCH_STATES,
    OVERRIDE_OUTCOMES,
    PROMOTION_STAGES,
    PROMOTION_TRANSITION_KINDS,
    SAFETY_ERROR_CATEGORIES,
    KillSwitchResult,
    OverrideContext,
    OverrideDecision,
    OverrideResult,
    PromotionDecision,
    PromotionResult,
    SafetyControlError,
    classify_promotion_demotion,
    evaluate_kill_switch,
    evaluate_override,
)

__all__ = [
    "ACTION_ERROR_CATEGORIES",
    "ADAPTER_ERROR_CATEGORIES",
    "ActionDescriptor",
    "ActionError",
    "AdapterError",
    "AdapterInput",
    "AdapterOutput",
    "AdapterProtocol",
    "AdapterResult",
    "AnyOf",
    "Condition",
    "DeterministicFacts",
    "ERROR_CATEGORIES",
    "EVIDENCE_ERROR_CATEGORIES",
    "EvidenceError",
    "EvidencePack",
    "EvidencePackManifest",
    "EvidenceVerificationResult",
    "EvidenceVerifierResult",
    "GATE_EVALUATION_ERROR_CATEGORIES",
    "GATE_STATUSES",
    "GENESIS_PREV_HASH",
    "Gate",
    "GateEvaluation",
    "GateEvaluationError",
    "GateResult",
    "KILL_SWITCH_OUTCOMES",
    "KILL_SWITCH_STATES",
    "KillSwitchResult",
    "LEDGER_ERROR_CATEGORIES",
    "LedgerEntry",
    "LedgerError",
    "LedgerReplayMatch",
    "LedgerVerificationResult",
    "ModelDerivedJudgments",
    "OVERRIDE_OUTCOMES",
    "OverrideContext",
    "OverrideDecision",
    "OverrideEvidence",
    "OverrideResult",
    "POLICY_VERDICT_DECISIONS",
    "PROMOTION_STAGES",
    "PROMOTION_TRANSITION_KINDS",
    "Policy",
    "PolicyError",
    "PolicyVerdict",
    "PromotionDecision",
    "PromotionResult",
    "RISK_TIERS",
    "SAFETY_ERROR_CATEGORIES",
    "SafetyControlError",
    "SyntheticAdapter",
    "ValidationResult",
    "adapt_payload",
    "append_ledger_entry",
    "build_evidence_pack",
    "canonicalize_ledger_entry",
    "classify_promotion_demotion",
    "collect_errors",
    "compute_ledger_entry_hash",
    "evaluate_action",
    "evaluate_kill_switch",
    "evaluate_override",
    "evidence_pack_to_canonical_json",
    "resolve_field",
    "validate_action",
    "verify_evidence",
    "verify_evidence_pack",
    "verify_ledger_chain",
]
